---
stages: [check, deploy]
variables:
  GIT_STRATEGY: clone
  SHELLCHECK_OPTS: "-e SC2034 -e SC2148"
check:
  stage: check
  image: nixpkgs/nix-flakes:latest
  script:
    - nix flake update # fix me: source not found if not run
    - nix flake check -L || true # this can be removed once issues are fixed
  rules:
    - if: $CI_COMMIT_BRANCH == "testing"
      when: always
deploy:
  stage: deploy
  image: nixpkgs/nix-flakes:latest
  script:
    - nix flake update # fix me: source not found if not run
    - nix run .#deployer
  rules:
    - if: $CI_COMMIT_BRANCH != "testing"
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /^deploy/
