---
stages: [check, deploy]
variables:
  GIT_STRATEGY: clone
  REPO_URL: $CI_SERVER_PROTOCOL://gitlab-ci-token:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
  SHELLCHECK_OPTS: "-e SC2034 -e SC2148"
check:
  stage: check
  image: nixpkgs/nix-flakes:latest
  script:
    - nix flake update # fix me: source not found if not run
    - nix flake check -L || true
  only:
    refs: [testing]
deploy:
  stage: deploy
  image: nixpkgs/nix-flakes:latest
  script:
    - nix run .#deployer
  only:
    refs: [testing]
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[deploy\]/
