---
stages: [check, check-pr, bumpver, deploy]

variables:
  BUILD_HOST: builds.garudalinux.org
  BUILD_PORT: 223
  BUILD_USER: gitlab
  GIT_AUTHOR_EMAIL: ci@garudalinux.org
  GIT_AUTHOR_NAME: GitLab CI
  GIT_STRATEGY: clone
  REPO_URL: $CI_SERVER_PROTOCOL://gitlab-ci-token:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git

check:
  # Check the PKGBUILD and install files for common bash anti-patterns and issues
  stage: check
  image: alpine:latest
  inherit:
    variables: false
  script:
    - apk add --no-cache --upgrade bash npm py3-pip shellcheck shfmt
    - pip install yamllint
    - npm install -g markdownlint-cli
    - bash .ci/lint.sh
  rules:
    - if: $BUMPVER != "1"

check-pr:
  # Check the current commit message for compliance with commitizen
  stage: check-pr
  image: alpine:latest
  inherit:
    variables: false
  script:
    - apk add --no-cache --upgrade py3-pip
    - pip install -U commitizen
    - cz check --message "$CI_COMMIT_MESSAGE" >/tmp/cz_check || true # why does it return 1 if its actually 0?
    - grep "successful" /tmp/cz_check # ugly hack to workaround the above issue
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $BUMPVER != "1"

bumpver:
  # This basically updates the version in the PKGBUILD and commits it,
  # triggering an instant build of the package via commit message.
  stage: bumpver
  image: archlinux:latest
  script:
    - pacman -Syu --noconfirm curl git jq pacman-contrib
    - git config --global user.name "$GIT_AUTHOR_NAME"
    - git config --global user.email "$GIT_AUTHOR_EMAIL"
    - bash .ci/version-bump.sh
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $BUMPVER == "1"

deploy:
  # This only runs on the default branch and when the commit message contains [deploy *]
  # and is used to deploy the package to the build server.
  stage: deploy
  image: alpine:latest
  script:
    - '[[ -z ${DEPLOY_KEY+x} ]] && echo "No deploy key available, backing off!" && exit 1'
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$DEPLOY_KEY" >>~/.ssh/id_ed25519
    - chmod 400 ~/.ssh/id_ed25519
    - apk add --no-cache --upgrade bash openssh
    - bash .ci/what-to-deploy.sh
    - TO_DEPLOY=$(cat /tmp/TO_DEPLOY)
    - ssh -p "$BUILD_PORT" -o StrictHostKeyChecking=no "$BUILD_USER"@"$BUILD_HOST" "chaotictrigger $TO_DEPLOY"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE =~ /\[deploy.*\]/ && $BUMPVER != "1"
