---
stages: [check, deploy]
variables:
  GIT_STRATEGY: clone
  SHELLCHECK_OPTS: "-e SC2034 -e SC2148"
check:
  stage: check
  image: nixpkgs/nix-flakes:latest
  script:
    - nix flake update # fix me: source not found if not run
    - nix flake check -L || true # this can be removed once issues are fixed
  only:
    refs: [testing]
deploy:
  stage: deploy
  image: nixpkgs/nix-flakes:latest
  script:
    - nix run .#deployer
  only:
    refs: [testing]
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[deploy\/
