---
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages: [check, check-pr, deploy]

variables:
  BUILD_HOST: builds.garudalinux.org
  BUILD_PORT: 223
  BUILD_USER: gitlab
  GIT_STRATEGY: clone

check:
  stage: check
  image: alpine:latest
  script:
    - apk add --no-cache --upgrade bash shellcheck shfmt
    - bash .ci/lint.sh || true

check-pr:
  stage: check-pr
  image: commitizen/commitizen:3
  script:
    - cz check -m "$CI_COMMIT_MESSAGE"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - | # Initialize deployment
      [[ -z "${DEPLOY_KEY+x}" ]] && echo "No deploy key available, backing off!" && exit 1
      mkdir -p ~/.ssh
      chmod 700 ~/.ssh
      echo "$DEPLOY_KEY" >>~/.ssh/id_ed25519
      chmod 400 ~/.ssh/id_ed25519
      apk add --no-cache --upgrade bash openssh
    - | # Determine what to deploy
      bash .ci/what-to-deploy.sh
    - | # Trigger deployment
      TO_DEPLOY=$(cat /tmp/TO_DEPLOY)
      ssh -p "$BUILD_PORT" -o StrictHostKeyChecking=no "$BUILD_USER"@"$BUILD_HOST" "chaotictrigger $TO_DEPLOY"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE =~ /\[deploy.*\]/
